# Generated by Django 3.2.15 on 2022-09-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resenia', models.CharField(max_length=50)),
                ('puntuacion', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('contenido', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='tapas/')),
            ],
        ),
    ]
