# Generated by Django 3.2.15 on 2022-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_peliculas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='horario',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='lugar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='sipnosis',
            field=models.TextField(blank=True),
        ),
    ]
