# Generated by Django 3.2.15 on 2022-09-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220929_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='imagen',
            field=models.CharField(max_length=100),
        ),
    ]
